### ISSUE TITLE
Will the source code of LSPConvert.exe be available?

### ISSUE THREAD

**Issue by tehKaiN** [arnaud-carre/LSPlayer#2]
I'd love to take a look on how this works!

**Comment by arnaud-carre** [comment]
yes I will publish the source code probably during the year. I want to fix all bugs that people are reporting and cleanup the source code a bit.

**Comment by mankeli** [comment]
hoping for this too!

**Comment by MBeijer** [comment]
+1

**Comment by arnaud-carre** [comment]
things are taking longer than expected because in between I added a different data model, suited for "small" intro like 4KiB. ( I mean highly compressible ). I have several data format right now but want LSP to be simple and straightforward so I have to cut some of them to probably have two formats:
- the current one ( very fast one, reasonable size in memory & packed on disk )
- the "tiny" one ( slightly slower replay code, large size in memory, but small disk footprint )

**Comment by ilo-3a29** [comment]
Hi,
I'd love to have access to the source code for the converter so I can make builds for Mac, has there been any progress on open sourcing (or could I get the source to make mac/linux versions)?

**Comment by arnaud-carre** [comment]
the source code is fully available now! enjoy!
